import { AfterViewChecked, AfterViewInit, ElementRef, EventEmitter, OnDestroy, Renderer2 } from '@angular/core';
import { ControlValueAccessor } from '@angular/forms';
import { RadioButton } from './radio-button.interface';
import { RadioGroupComponent } from './radio-group.component';
import { NgxSize } from './typings';
import * as i0 from "@angular/core";
export declare class RadioButtonComponent implements RadioButton, AfterViewChecked, AfterViewInit, OnDestroy, ControlValueAccessor {
    private elementRef;
    private renderer;
    radioGroupComp: RadioGroupComponent;
    id: string;
    checked: boolean;
    disabled: boolean;
    ngxColor: string;
    ngxValue: string;
    ngxSize: NgxSize | number;
    onclick: EventEmitter<RadioButton>;
    inputRadioRef: ElementRef;
    private subscription;
    onChange: any;
    onTouched: any;
    constructor(elementRef: ElementRef, renderer: Renderer2, radioGroupComp: RadioGroupComponent);
    ngOnDestroy(): void;
    eventChecked(event: Event): void;
    onClick(): void;
    ngAfterViewChecked(): void;
    ngAfterViewInit(): void;
    setSizeInNumber(): void;
    writeValue(value: boolean): void;
    registerOnChange(fn: any): void;
    registerOnTouched(fn: any): void;
    setDisabledState?(disabled: boolean): void;
    setAccentColor(): void;
    static ɵfac: i0.ɵɵFactoryDeclaration<RadioButtonComponent, [null, null, { optional: true; host: true; }]>;
    static ɵcmp: i0.ɵɵComponentDeclaration<RadioButtonComponent, "ngx-radio-button", never, { "checked": { "alias": "checked"; "required": false; }; "ngxColor": { "alias": "ngxColor"; "required": false; }; "ngxValue": { "alias": "ngxValue"; "required": false; }; "ngxSize": { "alias": "ngxSize"; "required": false; }; }, { "onclick": "onclick"; }, never, ["*"], true, never>;
}
