import { AfterViewInit, ElementRef, EventEmitter, OnDestroy, QueryList, Renderer2, TemplateRef } from '@angular/core';
import { ControlValueAccessor, NgControl } from '@angular/forms';
import { StylesService } from 'ngx-eagle/core/services';
import { NgxOptionComponent } from '../ngx-option/ngx-option.component';
import { SelectedOption } from './selected-option.interface';
import * as i0 from "@angular/core";
export declare class NgxOutlinedSelectFieldComponent implements AfterViewInit, ControlValueAccessor, OnDestroy {
    elementRef: ElementRef;
    private renderer;
    private stylesService;
    ngControl: NgControl;
    optionList: QueryList<NgxOptionComponent>;
    autocomplete: boolean;
    disabled: boolean;
    label: string;
    multiple: boolean;
    pattern: any;
    placeholder: string;
    prefix: any | TemplateRef<void>;
    required: boolean;
    suffix: any | TemplateRef<void>;
    internalValue: any;
    selectedOptions: SelectedOption[];
    get value(): any;
    set value(value: any);
    isSelectedOption(elemento: any): elemento is SelectedOption | SelectedOption[];
    onChangeValue: EventEmitter<any>;
    _placeholder: string;
    errorText: string;
    inputPrefixId: string;
    optPos: 'bottom' | 'top';
    containerRef: ElementRef;
    labelRef: ElementRef;
    inputRef: ElementRef;
    optionsRef: ElementRef;
    borderColor: string;
    onChange: any;
    onTouched: any;
    private subscription;
    isValid: boolean;
    isFocused: boolean;
    autofilled: boolean;
    isOpenMultipleMode: boolean;
    constructor(elementRef: ElementRef, renderer: Renderer2, stylesService: StylesService, ngControl: NgControl);
    ngOnDestroy(): void;
    ngAfterViewInit(): void;
    mousedown(event: any): void;
    onKeyDown(event: KeyboardEvent): void;
    customProperties(): void;
    typeOf(value: any): "string" | "number" | "bigint" | "boolean" | "symbol" | "undefined" | "object" | "function";
    initialize(): void;
    writeValue(value: any): void;
    registerOnChange(fn: any): void;
    registerOnTouched(fn: any): void;
    setDisabledState(isDisabled: boolean): void;
    singleInputValue(value: any): void;
    multipleInputValues(selectedOptions: any): void;
    selectMultipleOptions(selectedOptions: SelectedOption[]): void;
    multiSelectionOnClick(value: any): void;
    moveLabel(): void;
    private applyFocusedStyle;
    private applyDefaultStyle;
    private setLabelStyle;
    prefixWidth(): number;
    onInput(event: Event): void;
    onSearch(event: Event): void;
    onFocus(event: FocusEvent): void;
    onResize(): void;
    adjustOptionsPosition(): void;
    showBackdrop(): void;
    hideBackdrop(): void;
    onBlur(event: FocusEvent): void;
    buildBorderOutlined(): void;
    private calculateBorderPercent;
    private calculateBackgroundStyle;
    drawLineTopBorder(): void;
    setBorderTop(border: string): void;
    validate(): void;
    isValidValue(value: any): boolean;
    static ɵfac: i0.ɵɵFactoryDeclaration<NgxOutlinedSelectFieldComponent, [null, null, null, { optional: true; self: true; }]>;
    static ɵcmp: i0.ɵɵComponentDeclaration<NgxOutlinedSelectFieldComponent, "ngx-outlined-select-field", never, { "autocomplete": { "alias": "autocomplete"; "required": false; }; "disabled": { "alias": "disabled"; "required": false; }; "label": { "alias": "label"; "required": false; }; "multiple": { "alias": "multiple"; "required": false; }; "pattern": { "alias": "pattern"; "required": false; }; "placeholder": { "alias": "placeholder"; "required": false; }; "prefix": { "alias": "prefix"; "required": false; }; "required": { "alias": "required"; "required": false; }; "suffix": { "alias": "suffix"; "required": false; }; "value": { "alias": "value"; "required": false; }; }, { "onChangeValue": "onChangeValue"; }, ["optionList"], ["*"], true, never>;
    static ngAcceptInputType_autocomplete: unknown;
    static ngAcceptInputType_disabled: unknown;
    static ngAcceptInputType_multiple: unknown;
    static ngAcceptInputType_required: unknown;
}
