import { AfterViewInit, ElementRef, OnDestroy, Renderer2, TemplateRef } from '@angular/core';
import { ControlValueAccessor, NgControl } from '@angular/forms';
import { StylesService } from 'ngx-eagle/core/services';
import { NgxType } from '../typings';
import * as i0 from "@angular/core";
export declare class NgxOutlinedTextFieldComponent implements AfterViewInit, ControlValueAccessor, OnDestroy {
    elementRef: ElementRef;
    private renderer;
    private stylesService;
    ngControl: NgControl;
    autocomplete: string;
    disabled: boolean;
    label: string;
    pattern: any;
    placeholder: string;
    prefix: any | TemplateRef<void>;
    required: boolean;
    rows: number;
    suffix: any | TemplateRef<void>;
    type: NgxType;
    value: any;
    _placeholder: string;
    errorText: string;
    inputPrefixId: string;
    containerRef: ElementRef;
    labelRef: ElementRef;
    inputRef: ElementRef;
    borderColor: string;
    onChange: any;
    onTouched: any;
    isValid: boolean;
    isFocused: boolean;
    private autofilledSubscription;
    autofilled: boolean;
    constructor(elementRef: ElementRef, renderer: Renderer2, stylesService: StylesService, ngControl: NgControl);
    ngOnDestroy(): void;
    ngAfterViewInit(): void;
    autofillMonitor(): void;
    customProperties(): void;
    typeOf(value: any): "string" | "number" | "bigint" | "boolean" | "symbol" | "undefined" | "object" | "function";
    initialize(): void;
    writeValue(value: any): void;
    registerOnChange(fn: any): void;
    registerOnTouched(fn: any): void;
    setDisabledState(isDisabled: boolean): void;
    moveLabel(): void;
    private applyFocusedStyle;
    private applyDefaultStyle;
    private setLabelStyle;
    prefixWidth(): number;
    onInput(event: Event): void;
    onFocus(event: FocusEvent): void;
    onBlur(event: FocusEvent): void;
    buildBorderOutlined(): void;
    private calculateBorderPercent;
    private calculateBackgroundStyle;
    drawLineTopBorder(): void;
    setBorderTop(border: string): void;
    validate(): void;
    isValidValue(value: any): boolean;
    static ɵfac: i0.ɵɵFactoryDeclaration<NgxOutlinedTextFieldComponent, [null, null, null, { optional: true; self: true; }]>;
    static ɵcmp: i0.ɵɵComponentDeclaration<NgxOutlinedTextFieldComponent, "ngx-outlined-text-field", never, { "autocomplete": { "alias": "autocomplete"; "required": false; }; "disabled": { "alias": "disabled"; "required": false; }; "label": { "alias": "label"; "required": false; }; "pattern": { "alias": "pattern"; "required": false; }; "placeholder": { "alias": "placeholder"; "required": false; }; "prefix": { "alias": "prefix"; "required": false; }; "required": { "alias": "required"; "required": false; }; "rows": { "alias": "rows"; "required": false; }; "suffix": { "alias": "suffix"; "required": false; }; "type": { "alias": "type"; "required": false; }; "value": { "alias": "value"; "required": false; }; }, {}, never, never, true, never>;
    static ngAcceptInputType_disabled: unknown;
    static ngAcceptInputType_required: unknown;
    static ngAcceptInputType_rows: unknown;
}
